---
header-includes:
  - \usepackage{threeparttable}

title: "A Comprehensive Look at Financial Volatility Prediction by Economic Variables"
subtitle: "Updated Data"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, message = FALSE}
library("dplyr")
library("googlesheets4")
library("gt")
library("kableExtra")

sheet_google <- "https://docs.google.com/spreadsheets/d/16_qOe2WktZrdkOmHkaLr8FSWiKfJKOn-dK2NkS-GY68/edit#gid=0"
sheets_deauth()

aux_a <- read_sheet(sheet_google, sheet = "Hoja 1") 
aux_b <- read_sheet(sheet_google, sheet = "Hoja 2") 

short_sample_tbl <- openxlsx::read.xlsx(here::here("data", 
                                                   "short_sample_updated.xlsx"),
                                         sheet = 1) %>% 
  janitor::clean_names()

rv_stocks_tbl <- openxlsx::read.xlsx(here::here("data",
                                                "short_sample_updated.xlsx"), 
                                     sheet = 2) %>% 
  janitor::clean_names()

data_l <- readr::read_csv(here::here("data-raw", "css_rvprl.csv"))
data_s <- readr::read_csv(here::here("data-raw", "css_rvprs.csv"))
```


```{r, echo = FALSE, message = FALSE}
# overview rv short from paper data from 1983-01 to 2010-12
rv_stocks_paper <- data_l %>% 
  janitor::clean_names() %>% 
  select(date, rv_stocks) %>%
  filter(date >=198301) %>% 
  mutate(rv_stocks = log(rv_stocks)) %>%
  select(-date) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                         sd(x, na.rm = TRUE),
                         PerformanceAnalytics::skewness(x, na.rm = TRUE),
                         PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                        method = "moment"),
                         acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>% 
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(), list(~ round(as.numeric(.), 2))) %>% 
  mutate(variable = case_when(
    variable == "rv_stocks" ~ "Stocks (1982-2010) Christiansen et al."
  ))

# overview rv short from 1983-01 to 2010-12
rv_stocks_replication <- rv_stocks_tbl %>% 
  janitor::clean_names() %>% 
  select(yyyymm, rv) %>%
  filter(yyyymm >=198301 & yyyymm <= 201012) %>% 
  mutate(rv = log(rv)) %>%
  select(-yyyymm) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                         sd(x, na.rm = TRUE),
                         PerformanceAnalytics::skewness(x, na.rm = TRUE),
                         PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                        method = "moment"),
                         acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>% 
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(), list(~ round(as.numeric(.), 2))) %>% 
  mutate(variable = case_when(
    variable == "rv" ~ "Stocks (1982-2010)"
  ))

# overview rv short updated from 1983-01 to 2018-12
rv_stocks_replication_updated <- rv_stocks_tbl %>% 
  janitor::clean_names() %>% 
  select(yyyymm, rv) %>%
  filter(yyyymm >=198301) %>% 
  mutate(rv = log(rv)) %>%
  select(-yyyymm) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                         sd(x, na.rm = TRUE),
                         PerformanceAnalytics::skewness(x, na.rm = TRUE),
                         PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                        method = "moment"),
                         acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>% 
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(), list(~ round(as.numeric(.), 2))) %>% 
  mutate(variable = case_when(
    variable == "rv" ~ "Stocks (1982-2018)"
  ))

# table
rbind(rv_stocks_paper,
      rv_stocks_replication,
      rv_stocks_replication_updated) %>% 
  rename(`Volatility` = variable,
         `Std.` = Std, `Skew.` = Skew, `Kurt.` = Kurt) %>% 
  mutate_at(vars(Mean:`AC(1)`), list(~ round(., 2))) %>% 
  kable("latex", booktabs = T, 
        caption = "Overview Realized Volatility by the Original Authors: From 01/1983 to 12/2010", 
        linesep = " ",
        align = "l") %>%
  kable_styling("striped", "hold_position", full_width = F)
```

```{r, echo = FALSE, message = FALSE}
# overview variables long from paper data from 1983-01 to 2010-12
descp_l <- data_l %>% 
  janitor::clean_names() %>% 
  filter(date >= 198301) %>% 
  select(c(d_p:infm)) %>% 
  mutate_at(vars(mkt:infm), list(~ 100 * .)) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                         sd(x, na.rm = TRUE),
                         PerformanceAnalytics::skewness(x, na.rm = TRUE),
                         PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                        method = "moment"),
                         acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>% 
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(Mean:`AC(1)`), list(~ round(as.numeric(.), 2))) 

# overview variables short from paper data from 1983-01 to 2010-12
descp_s <- data_s %>% 
  janitor::clean_names() %>% 
  select(c(turn:pmi)) %>% 
  mutate_at(vars(msci, bas:ps, infa:conf), list(~ 100 * .)) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                         sd(x, na.rm = TRUE),
                         PerformanceAnalytics::skewness(x, na.rm = TRUE),
                         PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                        method = "moment"),
                         acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>% 
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(Mean:`AC(1)`), list(~ round(as.numeric(.), 2))) 

# overview variables short from 1983-01 to 2010-12
short_descriptive_stats_paper <- short_sample_tbl %>% 
  filter(yyyymm >= 198301 & yyyymm <= 201012) %>%
  select(-c(yyyymm:month)) %>% 
  mutate_at(vars(mkt:conf), list(~ 100 * (.))) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                               sd(x, na.rm = TRUE),
                               PerformanceAnalytics::skewness(x, na.rm = TRUE),
                               PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                              method = "moment"),
                               acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>%   
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(Mean:`AC(1)`), list(~ round(as.numeric(.), 2))) 

# overview variables short 1983-01 to 2018-12
short_descriptive_stats_updated <- short_sample_tbl %>% 
  filter(yyyymm >= 198301 & yyyymm <= 201812) %>%
  select(-c(yyyymm:month)) %>% 
  mutate_at(vars(mkt:conf), list(~ 100 * (.))) %>% 
  purrr::map(function(x) cbind(mean(x, na.rm = TRUE),
                               sd(x, na.rm = TRUE),
                               PerformanceAnalytics::skewness(x, na.rm = TRUE),
                               PerformanceAnalytics::kurtosis(x, na.rm = TRUE, 
                                                              method = "moment"),
                               acf(x, plot = FALSE)[[1]][2])) %>% 
  bind_rows() %>%   
  t() %>% 
  `colnames<-`(c('Mean', 'Std', "Skew", "Kurt", "AC(1)")) %>% 
  as_tibble(rownames = NA) %>% 
  mutate(variable = rownames(.)) %>% 
  select(variable, Mean, Std, Skew, Kurt, `AC(1)`) %>% 
  mutate_at(vars(Mean:`AC(1)`), list(~ round(as.numeric(.), 2))) 
```

```{r, echo = FALSE, message = FALSE}
# not all predictors was finded
match_var <- c("d_p", "e_p", "mkt", "smb", "hml", "str", "msci", 
               "t_b", "rtb", "ltr", "rbr", "t_s", "def", "ps", 
               "ted", "infm", "infa", "ipm", "ipga", "h_s", "m1m", 
               "m1a", "ordm", "orda", "crb", "cap", "empl", 
               "sent", "conf", "diff", "pmbb", "pmi")

# filter and arrange variable for match with aux_a
side_b <- bind_rows(descp_l, descp_s) %>% 
  filter(variable %in% match_var) %>% 
  arrange(match(variable, match_var))

bind_cols(aux_a, side_b) %>%
  rename(`Std.` = Std, `Skew.` = Skew, `Kurt.` = Kurt) %>% 
  select(-c(variable, type)) %>% 
  kable("latex", booktabs = T, 
        caption = "Overview of Predictive Variables by the Original Authors: From 01/1983 to 12/2010", 
        linesep = " ",
        align = "l",
        escape = FALSE) %>%
  kable_styling(c("striped", "Hold_position"), full_width = F) %>%
  pack_rows("Equity Market Variables and Risk Factors", 1, 7, 
            italic = T, bold = F) %>%
  pack_rows("Interest rates, Spreads and Bond Market Factors", 8, 12, 
            italic = T, bold = F) %>% 
  pack_rows("Liquidity and Credit Risk Variables", 13, 15, 
            italic = T, bold = F) %>% 
  pack_rows("Macroeconomic Variables", 16, 32, 
            italic = T, bold = F) %>% 
  footnote(general = "An asterisk (*) denotes that the variable is alsopart of the Goyal and Welch (2008) dataset, † denotes that the variable is included in set of predictors in case of the long-term U.S. equity sample from 12/1926-12/2010.  The sample period over which the summary statistics for the predictors are computed is from 01/1983-12/2010.", footnote_as_chunk = T, threeparttable = TRUE, escape = TRUE)
```

```{r, echo = FALSE, message = FALSE}
bind_cols(aux_a, short_descriptive_stats_paper) %>% 
  rename(`Std.` = Std, `Skew.` = Skew, `Kurt.` = Kurt) %>% 
  select(-c(variable, type)) %>% 
  kable("latex", booktabs = T, 
        caption = "Overview of Predictive Variables: From 01/1983 to 12/2010", 
        linesep = " ",
        align = "l",
        escape = FALSE) %>%
  kable_styling(c("striped", "Hold_position"), full_width = F) %>%
  pack_rows("Equity Market Variables and Risk Factors", 1, 7, 
            italic = T, bold = F) %>%
  pack_rows("Interest rates, Spreads and Bond Market Factors", 8, 12, 
            italic = T, bold = F) %>% 
  pack_rows("Liquidity and Credit Risk Variables", 13, 15, 
            italic = T, bold = F) %>% 
  pack_rows("Macroeconomic Variables", 16, 32, 
            italic = T, bold = F) %>% 
  footnote(general = "An asterisk (*) denotes that the variable is alsopart of the Goyal and Welch (2008) dataset, † denotes that the variable is included in set of predictors in case of the long-term U.S. equity sample from 12/1926-12/2010.  The sample period over which the summary statistics for the predictors are computed is from 01/1983-12/2010.", footnote_as_chunk = T, threeparttable = TRUE, escape = TRUE)
```

```{r, echo = FALSE, message = FALSE}
bind_cols(aux_a, short_descriptive_stats_paper) %>% 
  rename(`Std.` = Std, `Skew.` = Skew, `Kurt.` = Kurt) %>% 
  select(-c(variable, type)) %>% 
  kable("latex", booktabs = T, 
        caption = "Overview of Predictive Variables: From 01/1983 to 12/2018", 
        linesep = " ",
        align = "l",
        escape = FALSE) %>%
  kable_styling(c("striped", "Hold_position"), full_width = F) %>%
  pack_rows("Equity Market Variables and Risk Factors", 1, 7, 
            italic = T, bold = F) %>%
  pack_rows("Interest rates, Spreads and Bond Market Factors", 8, 12, 
            italic = T, bold = F) %>% 
  pack_rows("Liquidity and Credit Risk Variables", 13, 15, 
            italic = T, bold = F) %>% 
  pack_rows("Macroeconomic Variables", 16, 32, 
            italic = T, bold = F) %>% 
  footnote(general = "An asterisk (*) denotes that the variable is alsopart of the Goyal and Welch (2008) dataset, † denotes that the variable is included in set of predictors in case of the long-term U.S. equity sample from 12/1926-12/2010.  The sample period over which the summary statistics for the predictors are computed is from 01/1983-12/2018.", footnote_as_chunk = T, threeparttable = TRUE, escape = TRUE)
```


```{r, echo = FALSE, message = FALSE}
aux_b %>% 
  select(-c(type)) %>% 
  kable("latex", booktabs = T, 
        caption = "Predictive Variables: Data Source and Construction", 
        linesep = " ",
        align = "l",
        escape = TRUE) %>%
  kable_styling(c("striped", "scale_down"), "hold_position", 
                full_width = F, font_size = 6) %>%
  pack_rows("Equity Market Variables and Risk Factors", 1, 7, 
            italic = T, bold = F) %>%
  pack_rows("Interest rates, Spreads and Bond Market Factors", 8, 12, 
            italic = T, bold = F) %>% 
  pack_rows("Liquidity and Credit Risk Variables", 13, 15, 
            italic = T, bold = F) %>% 
  pack_rows("Macroeconomic Variables", 16, 32, 
            italic = T, bold = F) %>% 
  column_spec(4, width = "45em") %>% 
  landscape()
```

